### ISSUE TITLE
Autocomplete CSS not loading

### ISSUE THREAD

**Issue by mkcgphy** [yoanmarchal/webpack-jquery-ui#30]
I am trying to use webpack for Autocomplete. I am following the link 

https://npm.runkit.com/webpack-jquery-ui/autocomplete.js?t=1569876630262 
  
I have used the following settings in my project : 

In Webpack.config.js : 

const path = require('path');
const webpack = require('webpack');
module.exports = {
  entry: {
    index:'./src/index.js'
  },
  output: {
    filename: 'bundled.js',
    path: path.resolve(__dirname, 'dist'),
    publicPath:'dist/'
  },
  module: {
    rules: [
      {
        test: /\.css$/,
        loaders: ["style-loader","css-loader"]
      },
      {
        test: /\.(jpe?g|png|gif)$/i,
        loader:"file-loader",
        options:{
          name:'[name].[ext]',
          outputPath:'assets/images/'
          //the images will be emited to dist/assets/images/ folder
        }
      }
    ]
  },
  plugins: [
    /* Use the ProvidePlugin constructor to inject jquery implicit globals */
    new webpack.ProvidePlugin({
        $: "jquery",
        jQuery: "jquery",
        "window.jQuery": "jquery'",
        "window.$": "jquery"
    })
  ]
};

In the index.ts file I am using 

import * as jQuery from 'jquery'
var autocomplete = require('jquery-ui/ui/widgets/autocomplete');

code is working perfectly but the css of autocomplete looks to be missing. Am I doing it right way. Please suggest.

**Comment by yoanmarchal** [comment]
u need to import css from jquery in your index.js file
`
import 'jquery-ui/themes/base/core.css';
import 'jquery-ui/themes/base/menu.css';
import 'jquery-ui/themes/base/autocomplete.css';
import 'jquery-ui/themes/base/theme.css';
`

**Comment by mkcgphy** [comment]
This is the main problem . The moment I use these import statements it starts throwing the error. 


[6:58:21] [build]  Initializing...
[6:58:21] [build]  Validating manifest...
[6:58:21] [build]  Validating control...
[6:58:22] [build]  Generating manifest types...
[6:58:22] [build]  Compiling and bundling control...
[Webpack stats]:
Hash: 1ebc4ca48a900299e095
Version: webpack 4.28.4
Time: 4546ms
Built at: 10/04/2019 6:58:27 AM
    Asset     Size  Chunks             Chunk Names
bundle.js  428 KiB    main  [emitted]  main
Entrypoint main = bundle.js
[./AddressValidationJQ/index.ts] 15.5 KiB {main} [built]
[./node_modules/jquery-ui/themes/base/autocomplete.css] 245 bytes {main} [built] [failed] [1 error]
[./node_modules/jquery-ui/themes/base/core.css] 235 bytes {main} [built] [failed] [1 error]
[./node_modules/jquery-ui/themes/base/menu.css] 231 bytes {main} [built] [failed] [1 error]
[./node_modules/jquery-ui/themes/base/theme.css] 306 bytes {main} [built] [failed] [1 error]
[./node_modules/jquery-ui/ui/keycode.js] 832 bytes {main} [built]
[./node_modules/jquery-ui/ui/position.js] 16.7 KiB {main} [built]
[./node_modules/jquery-ui/ui/safe-active-element.js] 1.01 KiB {main} [built]
[./node_modules/jquery-ui/ui/unique-id.js] 1010 bytes {main} [built]
[./node_modules/jquery-ui/ui/version.js] 287 bytes {main} [built]
[./node_modules/jquery-ui/ui/widget.js] 21.1 KiB {main} [built]
[./node_modules/jquery-ui/ui/widgets/autocomplete.js] 19.9 KiB {main} [built]
[./node_modules/jquery-ui/ui/widgets/menu.js] 19.2 KiB {main} [built]
[./node_modules/jquery/dist/jquery.js] 301 KiB {main} [built]

This is the latest snapshot of what I am getting. Am I missing something here ?

Thanks
